# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'BPSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BPSwift
   pod 'Bagel', '~> 1.3.1'
   pod 'Alamofire', '~> 4.8.1'
   pod 'SnapKit', '~> 4.2.0'

  target 'BPSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BPSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
